/*
 * Firebase Web SDK configuration.
 * Auto-generated by scripts/setup_firebase.sh on 2026-09-16T03:16:15.978Z
 *
 * Public client configuration. Zero private keys, zero passwords.
 */
window.PUICHING_SYNC_CONFIG = {
  "enabled": true,
  "apiKey": "AIzaSyBnd-HBwFzdR8lO-Wg21s7QnFO3qB0ZFkI",
  "authDomain": "puiching-eclass.firebaseapp.com",
  "databaseURL": "https://puiching-eclass-default-rtdb.asia-southeast1.firebasedatabase.app",
  "projectId": "puiching-eclass",
  "storageBucket": "puiching-eclass.firebasestorage.app",
  "messagingSenderId": "110494414346",
  "appId": "1:110494414346:web:8f63e24d61463e7fb3d1f3"
};
