#!/usr/bin/env bash
# ==============================================================================
# scripts/setup_firebase.sh
# Automated Firebase Realtime Database & Anonymous Auth Provisioning Script
# ==============================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"

echo "==> [1/6] 檢查環境依賴 (Node, npx, Firebase CLI)..."
if ! command -v npx >/dev/null 2>&1; then
  echo "錯誤: 系統未安裝 npx。請先安裝 Node.js (https://nodejs.org)。" >&2
  exit 1
fi

FIREBASE_BIN="npx -y firebase-tools@latest"
echo "Firebase CLI 準備就緒"

echo "==> [2/6] 檢查 Firebase 登入狀態與專案..."
PROJECT_ID="${1:-${FIREBASE_PROJECT_ID:-}}"

if [ -z "$PROJECT_ID" ]; then
  # 嘗試自 .firebaserc 讀取現有專案
  if [ -f "${ROOT_DIR}/.firebaserc" ]; then
    PROJECT_ID=$(grep -o '"default": *"[^"]*"' "${ROOT_DIR}/.firebaserc" | head -n1 | cut -d'"' -f4 || true)
  fi
fi

if [ -z "$PROJECT_ID" ]; then
  # 檢查是否在互動終端
  if [ -t 0 ]; then
    read -r -p "請輸入 Firebase Project ID (若留空將自動建立新專案): " INPUT_PROJ
    PROJECT_ID="$INPUT_PROJ"
  fi
fi

if [ -z "$PROJECT_ID" ]; then
  RANDOM_SUFFIX=$(od -An -N4 -tu4 /dev/urandom 2>/dev/null | tr -d ' ' | cut -c1-6 || echo "$(( RANDOM % 900000 + 100000 ))")
  PROJECT_ID="puiching-hw-${RANDOM_SUFFIX}"
  echo "正在嘗試建立新 Firebase 專案: ${PROJECT_ID}..."
  $FIREBASE_BIN projects:create "${PROJECT_ID}" --display-name "培正功課同步" || {
    echo "專案建立失敗或配額不足。請指定既有專案 ID: ./scripts/setup_firebase.sh <PROJECT_ID>" >&2
    exit 1
  }
fi

echo "使用專案: ${PROJECT_ID}"
$FIREBASE_BIN use "${PROJECT_ID}" --add 2>/dev/null || $FIREBASE_BIN use "${PROJECT_ID}"

echo "==> [3/6] 配置 firebase.json 與安全性規則..."
cat << 'EOF' > "${ROOT_DIR}/firebase.json"
{
  "database": {
    "rules": "firebase.rules.json"
  },
  "auth": {
    "providers": {
      "anonymous": true
    }
  }
}
EOF

echo "部署 Realtime Database 安全規則..."
$FIREBASE_BIN deploy --only database || {
  echo "提示: 若尚未建立 Database Instance，正在嘗試建立..."
  $FIREBASE_BIN database:instances:create "${PROJECT_ID}-default-rtdb" --location asia-southeast1 2>/dev/null || \
  $FIREBASE_BIN database:instances:create "${PROJECT_ID}" --location us-central1 2>/dev/null || true
  $FIREBASE_BIN deploy --only database
}

echo "啟用匿名認證 (Anonymous Auth)..."
$FIREBASE_BIN deploy --only auth 2>/dev/null || {
  echo "提示: 若 CLI deploy auth 不受專案支援，請確保在 Firebase Console > Authentication > Sign-in method 啟用了 Anonymous。"
}

echo "==> [4/6] 註冊 Web App 並取得 Web SDK Config..."
WEB_APP_ID=$($FIREBASE_BIN apps:list WEB --json 2>/dev/null | grep -o '"appId": *"[^"]*"' | head -n1 | cut -d'"' -f4 || true)
if [ -z "$WEB_APP_ID" ]; then
  echo "正在註冊 Web App (puiching-web)..."
  $FIREBASE_BIN apps:create WEB "puiching-web" --project "${PROJECT_ID}" || true
fi

echo "提取 Web SDK 設定..."
SDK_JSON=$($FIREBASE_BIN apps:sdkconfig WEB --json --project "${PROJECT_ID}")

echo "==> [5/6] 寫入 sync-config.js..."
if command -v node >/dev/null 2>&1; then
  node -e '
const fs = require("fs");
const raw = JSON.parse(process.argv[1]);
const cfg = (raw.result && raw.result.sdkConfig) ? raw.result.sdkConfig : (raw.sdkConfig || raw);

if (!cfg.databaseURL) {
  cfg.databaseURL = "https://" + (cfg.projectId || process.argv[2]) + "-default-rtdb.asia-southeast1.firebasedatabase.app";
}

const content = `/*
 * Firebase Web SDK configuration.
 * Auto-generated by scripts/setup_firebase.sh on ${new Date().toISOString()}
 *
 * Public client configuration. Zero private keys, zero passwords.
 */
window.PUICHING_SYNC_CONFIG = ${JSON.stringify({
  enabled: true,
  apiKey: cfg.apiKey || "",
  authDomain: cfg.authDomain || "",
  databaseURL: cfg.databaseURL || "",
  projectId: cfg.projectId || process.argv[2],
  storageBucket: cfg.storageBucket || "",
  messagingSenderId: cfg.messagingSenderId || "",
  appId: cfg.appId || ""
}, null, 2)};
`;

fs.writeFileSync(process.argv[3], content, "utf8");
console.log("已成功更新 sync-config.js！");
' "$SDK_JSON" "$PROJECT_ID" "${ROOT_DIR}/sync-config.js"
else
  python3 -c '
import sys, json, datetime
raw = json.loads(sys.argv[1])
project_id = sys.argv[2]
target_file = sys.argv[3]

cfg = raw.get("result", {}).get("sdkConfig", raw.get("sdkConfig", raw))
if not cfg.get("databaseURL"):
    cfg["databaseURL"] = f"https://{cfg.get(\"projectId\", project_id)}-default-rtdb.asia-southeast1.firebasedatabase.app"

iso_now = datetime.datetime.now(datetime.timezone.utc).isoformat()
config_obj = {
    "enabled": True,
    "apiKey": cfg.get("apiKey", ""),
    "authDomain": cfg.get("authDomain", ""),
    "databaseURL": cfg.get("databaseURL", ""),
    "projectId": cfg.get("projectId", project_id),
    "storageBucket": cfg.get("storageBucket", ""),
    "messagingSenderId": cfg.get("messagingSenderId", ""),
    "appId": cfg.get("appId", "")
}

content = f"""/*
 * Firebase Web SDK configuration.
 * Auto-generated by scripts/setup_firebase.sh on {iso_now}
 *
 * Public client configuration. Zero private keys, zero passwords.
 */
window.PUICHING_SYNC_CONFIG = {json.dumps(config_obj, indent=2)};
"""
with open(target_file, "w", encoding="utf-8") as f:
    f.write(content)
print("已成功更新 sync-config.js！")
' "$SDK_JSON" "$PROJECT_ID" "${ROOT_DIR}/sync-config.js"
fi

echo "==> [6/6] 驗證設置..."
if grep -q 'apiKey: ""' "${ROOT_DIR}/sync-config.js"; then
  echo "警告: sync-config.js 中的 apiKey 仍為空，請檢查 Firebase Console 設定。" >&2
  exit 1
fi

echo "✅ Firebase 自動化配置全部完成！"
echo "請啟動網頁伺服器（例如 python3 -m http.server 8000）並開啟 index.html 開始使用。"
